'use client'

import { TodoForm } from '../TodoForm'
import { EditTodoForm } from '../EditTodoForm'
import { TodoNote } from '../TodoNote'
import { useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
uuidv4()

/**
 * A React functional component that serves as a container for managing a list of todo tasks.
 *
 * This component maintains its own state of todos using the useState hook, where each todo object includes:
 *   - id: A unique identifier generated by uuidv4().
 *   - task: A description of the todo.
 *   - completed: A boolean indicating if the todo is completed (defaults to false).
 *   - isEditing: A boolean indicating if the todo is currently in editing mode (defaults to false).
 *
 * The component provides several functionalities:
 *   - addTodo: Adds a new todo to the list.
 *   - toggleComplete: Toggles the completion status of a specified todo.
 *   - deleteTodo: Removes a specified todo from the list.
 *   - editTodo: Toggles the editing state of a specified todo.
 *   - updateNote: Updates the task description of a specified todo and toggles its editing mode.
 *
 * It renders a header, a TodoForm for adding new todos, and for each todo, it conditionally renders either an
 * EditTodoForm (if the todo is in editing mode) or a TodoNote, passing relevant properties and event handlers.
 *
 * @param {Object} props - The component properties.
 * @returns {JSX.Element} The rendered TodoWrapper component.
 *
 * @example
 * <TodoWrapper />
 */
export function TodoWrapper(props) {
  const [todos, setTodos] = useState([])

  // Add a todo object
  const addTodo = (todo) => {
    console.log('Adding Todo: ', todo)
    setTodos([
      ...todos,
      { id: uuidv4(), task: todo, completed: false, isEditing: false },
    ])
  }

  // Strikethrough todo title to indicate completed state (toggle)
  const toggleComplete = (id) => {
    console.log('Setting Todo with id: ' + id)
    setTodos(() =>
      todos.map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo
      )
    )
  }

  // Delete todo note
  const deleteTodo = (id) => {
    console.log('Deleting Todo with id: ' + id)
    setTodos(() => todos.filter((todo) => todo.id !== id))
  }

  // Edit todo note by re-using form
  const editTodo = (id) => {
    console.log('Editing Todo with id: ' + id)
    setTodos(() =>
      todos.map((todo) =>
        todo.id === id ? { ...todo, isEditing: !todo.isEditing } : todo
      )
    )
  }

  // Update todo note when EditTodoForm is submitted
  const updateNote = (id, task) => {
    console.log('Updating Todo with id: ' + id + ' with new task: ' + task)
    setTodos(() =>
      todos.map((todo) =>
        todo.id === id ? { ...todo, task, isEditing: !todo.isEditing } : todo
      )
    )
  }

  return (
    <div className="TodoWrapper">
      <h1>Get Things Done!</h1>
      <TodoForm addTodo={addTodo} />
      {todos.map((todo, index) => {
        return todo.isEditing ? (
          <EditTodoForm
            id={todo.id}
            key={index}
            todoNote={todo}
            updateNote={updateNote}
          />
        ) : (
          <TodoNote
            task={todo.task}
            key={index}
            id={todo.id}
            toggleComplete={toggleComplete}
            completed={todo.completed}
            deleteTodo={deleteTodo}
            editTodo={editTodo}
            editMode={todo.isEditing}
          />
        )
      })}
    </div>
  )
}
