name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check_admin:
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN: csiyang
    steps:
      - name: st1
        if: ${{ github.actor != env.NAME_ADMIN }}
        run: exit 1
      - name: st2
        if: ${{ github.actor == env.NAME_ADMIN }}
        run: echo "ok"
